version: '3.8'

services:
  vtt-creator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vtt-creator-app
    ports:
      - "80:80"
    volumes:
      - ./:/app
    restart: unless-stopped

